#!/usr/bin/env bash

# Generated by codex

INTERVAL="1.5"
MAX_ROUNDS="${MAX_ROUNDS:-60}"

RESET=$'\033[0m'
BOLD=$'\033[1m'
RED=$'\033[1;91m'
GREEN=$'\033[1;92m'
YELLOW=$'\033[1;93m'
CYAN=$'\033[1;96m'
MAGENTA=$'\033[1;95m'

TOPIC_EXPECTED=$(cat <<'EOF'
/clock
/gazebo/resource_paths
/imu
/model/vehicle/odometry
/model/vehicle/tf
/rgbd_camera/camera_info
/rgbd_camera/depth_image
/rgbd_camera/image
/rgbd_camera/points
/sensors/marker
/stats
/world/default/clock
/world/default/dynamic_pose/info
/world/default/pose/info
/world/default/scene/deletion
/world/default/scene/info
/world/default/state
/world/default/stats
/model/vehicle/cmd_vel
/model/vehicle/enable
/world/default/light_config
/world/default/material_color
EOF
)

SERVICE_EXPECTED=$(cat <<'EOF'
/gazebo/resource_paths/add
/gazebo/resource_paths/get
/gazebo/resource_paths/resolve
/gazebo/worlds
/imu/set_rate
/rgbd_camera/set_rate
/sensors/marker
/sensors/marker/list
/sensors/marker_array
/server_control
/world/default/control
/world/default/control/state
/world/default/create
/world/default/create/blocking
/world/default/create_multiple
/world/default/create_multiple/blocking
/world/default/declare_parameter
/world/default/disable_collision
/world/default/disable_collision/blocking
/world/default/enable_collision
/world/default/enable_collision/blocking
/world/default/entity/system/add
/world/default/generate_world_sdf
/world/default/get_parameter
/world/default/gui/info
/world/default/level/set_performer
/world/default/light_config
/world/default/light_config/blocking
/world/default/list_parameters
/world/default/playback/control
/world/default/remove
/world/default/remove/blocking
/world/default/scene/graph
/world/default/scene/info
/world/default/set_parameter
/world/default/set_physics
/world/default/set_physics/blocking
/world/default/set_pose
/world/default/set_pose/blocking
/world/default/set_pose_vector
/world/default/set_pose_vector/blocking
/world/default/set_spherical_coordinates
/world/default/set_spherical_coordinates/blocking
/world/default/state
/world/default/state_async
/world/default/system/info
/world/default/visual_config
/world/default/visual_config/blocking
/world/default/wheel_slip
/world/default/wheel_slip/blocking
EOF
)

TOPIC_MATCH_COUNT=0
SERVICE_MATCH_COUNT=0
ROUND_COUNT=0

TMP_FILES=()

cleanup() {
  for file in "${TMP_FILES[@]}"; do
    [ -n "$file" ] && [ -e "$file" ] && rm -f "$file"
  done
}

print_summary() {
  echo
  printf "%s%sCompleted.%s\n" "$BOLD" "$YELLOW" "$RESET"
  printf "%s%sTopic full matches:   %d/%d%s\n" \
    "$BOLD" "$GREEN" "$TOPIC_MATCH_COUNT" "$ROUND_COUNT" "$RESET"
  printf "%s%sService full matches: %d/%d%s\n" \
    "$BOLD" "$GREEN" "$SERVICE_MATCH_COUNT" "$ROUND_COUNT" "$RESET"
}

on_exit() {
  cleanup
}

on_interrupt() {
  print_summary
  cleanup
  exit 0
}

trap on_exit EXIT
trap on_interrupt INT TERM

make_tmp() {
  local tmp
  tmp=$(mktemp)
  TMP_FILES+=("$tmp")
  printf "%s" "$tmp"
}

normalize_to_file() {
  local content="$1"
  local file="$2"
  if [ -n "$content" ]; then
    printf "%s\n" "$content" | sed '/^[[:space:]]*$/d' | LC_ALL=C sort -u > "$file"
  else
    : > "$file"
  fi
}

run_check() {
  local label="$1"
  local command="$2"
  local expected_content="$3"
  local match_var="$4"

  local expected_file actual_file missing_file extra_file actual_output
  expected_file=$(make_tmp)
  actual_file=$(make_tmp)
  missing_file=$(make_tmp)
  extra_file=$(make_tmp)

  normalize_to_file "$expected_content" "$expected_file"

  if ! actual_output=$($command 2>&1); then
    printf "%s%s[%s] command failed:%s\n" "$BOLD" "$RED" "$label" "$RESET"
    printf "%s\n" "$actual_output"
    return 1
  fi

  normalize_to_file "$actual_output" "$actual_file"

  comm -23 "$expected_file" "$actual_file" > "$missing_file"
  comm -13 "$expected_file" "$actual_file" > "$extra_file"

  if [ ! -s "$missing_file" ] && [ ! -s "$extra_file" ]; then
    printf "%s%s[%s]%s round=%d %sFULL MATCH%s\n" \
      "$BOLD" "$GREEN" "$label" "$RESET" "$ROUND_COUNT" "$BOLD" "$RESET"
    printf "  expected=%s actual=%s matched=%sYES%s cumulative=%d/%d\n" \
      "$(wc -l < "$expected_file")" \
      "$(wc -l < "$actual_file")" \
      "$GREEN" "$RESET" \
      "$(( ${!match_var} + 1 ))" "$ROUND_COUNT"
    printf -v "$match_var" '%d' "$(( ${!match_var} + 1 ))"
    return 0
  fi

  printf "%s%s[%s]%s round=%d %sDIFF%s\n" \
    "$BOLD" "$RED" "$label" "$RESET" "$ROUND_COUNT" "$BOLD" "$RESET"
  printf "  expected=%s actual=%s cumulative=%d/%d\n" \
    "$(wc -l < "$expected_file")" \
    "$(wc -l < "$actual_file")" \
    "${!match_var}" "$ROUND_COUNT"

  if [ -s "$missing_file" ]; then
    printf "  %smissing:%s\n" "$MAGENTA" "$RESET"
    sed 's/^/    /' "$missing_file"
  fi

  if [ -s "$extra_file" ]; then
    printf "  %sextra:%s\n" "$RED" "$RESET"
    sed 's/^/    /' "$extra_file"
  fi

  return 0
}

printf "%s%sMonitoring gz topic/service lists every %ss for %s rounds.%s\n" \
  "$BOLD" "$CYAN" "$INTERVAL" "$MAX_ROUNDS" "$RESET"

while [ "$ROUND_COUNT" -lt "$MAX_ROUNDS" ]; do
  ROUND_COUNT=$((ROUND_COUNT + 1))
  printf "\n%s------------------------------------------------------------%s\n" "$BOLD" "$RESET"
  printf "%sRound #%d%s\n" "$BOLD" "$ROUND_COUNT" "$RESET"

  run_check "TOPIC" "gz topic --list" "$TOPIC_EXPECTED" "TOPIC_MATCH_COUNT"

  if [ "$ROUND_COUNT" -lt "$MAX_ROUNDS" ]; then
    sleep "$INTERVAL"
  fi

  run_check "SERVICE" "gz service --list" "$SERVICE_EXPECTED" "SERVICE_MATCH_COUNT"

  if [ "$ROUND_COUNT" -lt "$MAX_ROUNDS" ]; then
    sleep "$INTERVAL"
  fi
done

print_summary
