<package format="3">
  <name>topiclist_test</name>
  <version>0.0.0</version>
  <description>TODO</description>
  <license>Apache 2.0</license>
  <maintainer email="1409947012@qq.com">C88-YQ</maintainer>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>gz-transport</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
