- topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  lazy: true
  direction: ROS_TO_GZ

- topic_name: "odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  lazy: true
  direction: ROS_TO_GZ

# - topic_name: "enable"
#   ros_type_name: "std_msgs/msg/Bool"
#   gz_type_name: "gz.msgs.Boolean"
#   lazy: true
#   direction: ROS_TO_GZ

- topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  lazy: true
  direction: GZ_TO_ROS
